on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to Vagrant Registry'
        type: boolean
        default: false
        required: false

  workflow_call:
    inputs:
      publish:
        description: 'Publish to Vagrant Registry'
        type: boolean
        default: false
        required: false

    secrets:
      HCP_CLIENT_ID:
        description: 'HCP service principal client ID for publishing'
        required: false

      HCP_CLIENT_SECRET:
        description: 'HCP service principal client secret for publishing'
        required: false

env:
  # renovate: datasource=deb depName=packer
  PACKER_VERSION: '1.13.1-1'
  # renovate: datasource=deb depName=vagrant
  VAGRANT_VERSION: '2.4.6-1'
  VAGRANT_BOX_UPDATE_CHECK_DISABLE: 1
  VAGRANT_CHECKPOINT_DISABLE: 1
  VAGRANT_FORCE_COLOR: 1
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - alpine319
          - alpine320
          - alpine321
          - alpine322
          - archlinux
          - debian13
          - fedora40
          - fedora41
          - fedora42
          - opensuseleap156
          - opensusetumbleweed
          - silverblue40
          - silverblue41
          - silverblue42
          - ubuntu2404
          - ubuntu2410
          - ubuntu2504
          - nixos

    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - run: nproc
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src
      - run: >-
          wget -O- https://apt.releases.hashicorp.com/gpg
          | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - run: >-
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - run: sudo apt-get update
      - run: >-
          sudo apt-get install -y --no-install-recommends
          "packer=$PACKER_VERSION"
          "vagrant=$VAGRANT_VERSION"
          qemu-system-x86
          qemu-system-modules-spice
          qemu-utils
          libvirt-daemon-system
          libvirt-dev
          dnsmasq
      - run: sudo apt-get clean -y
      - run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
      - run: sudo docker image prune --all --force
      - run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - run: packer init .
        working-directory: src
      - run: mkdir -p logs
      - run: >-
          packer build
          ${{ !inputs.publish && '-except vagrant-registry' || '' }}
          -only qemu.${{ matrix.build }}
          -var "log_dir=$GITHUB_WORKSPACE/logs"
          .
          2>&1
          | tee "$GITHUB_WORKSPACE/logs/packer.txt"
        working-directory: src
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          PACKER_LOG: 1
      - run: du -h *.box
        working-directory: src
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build }}-box
          path: src/*.box
          retention-days: 1
      - run: mkdir test
      - run: vagrant plugin install --verbose vagrant-libvirt
        working-directory: test
      - run: vagrant box add --clean --force --no-tty --name ${{ matrix.build }} ../src/*.box
        working-directory: test
      - run: rm src/*.box
      - run: vagrant init --template ../src/test/Vagrantfile.erb ${{ matrix.build }}
        working-directory: test
      - run: |
          sudo mkdir -p /etc/qemu
          echo "allow virbr0" | sudo tee /etc/qemu/bridge.conf
          sudo chmod u+s /usr/lib/qemu/qemu-bridge-helper
      - run: vagrant up --no-tty --debug
        working-directory: test
      - id: virt_domain_name
        run: echo "virt_domain_name=$(virsh --connect=qemu:///session --quiet list --name)" >>"$GITHUB_OUTPUT"
      - run: virsh --connect=qemu:///session screenshot "$VIRT_DOMAIN_NAME" --file logs/screenshot.png
        env:
          VIRT_DOMAIN_NAME: ${{ steps.virt_domain_name.outputs.virt_domain_name }}
      - run: vagrant destroy --force --graceful
        working-directory: test
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build }}-logs
          path: logs
        if: always()
