on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Box version'
        type: string
        required: false
        default: '0.0.0'
      publish:
        description: 'Publish to Vagrant Registry'
        type: boolean
        default: false
        required: false

  workflow_call:
    inputs:
      version:
        description: 'Box version'
        type: string
        required: false
        default: '0.0.0'
      publish:
        description: 'Publish to Vagrant Registry'
        type: boolean
        default: false
        required: false

    secrets:
      HCP_CLIENT_ID:
        description: 'HCP service principal client ID for publishing'
        required: false

      HCP_CLIENT_SECRET:
        description: 'HCP service principal client secret for publishing'
        required: false

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  PACKER_LOG: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - alpine318
          - alpine319
          - alpine320
          - debian12
          - fedora41
          - fedora40
          - opensuseleap156
          - opensusetumbleweed
          - silverblue41
          - silverblue40
          - ubuntu2204
          - ubuntu2404
          - ubuntu2410

    runs-on: ubuntu-24.04
    steps:
      - run: nproc
      - uses: actions/checkout@v4
      - run: >-
          wget -O- https://apt.releases.hashicorp.com/gpg
          | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - run: >-
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends packer qemu-system-x86 qemu-utils
      - run: sudo apt-get clean -y
      - run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
      - run: sudo docker image prune --all --force
      - run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - run: packer init .
      - run: >-
          packer build
          -var version=${{ inputs.version }}
          ${{ !inputs.publish && '-except vagrant-registry' || '' }}
          -only qemu.${{ matrix.build }}
          .
