name: pr

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      # Not: - reopened
    paths-ignore:
      - renovate.json
      - renovate-local-dry-run.sh
      - .gitattributes
      - .gitignore

concurrency:
  group: ${{ github.workflow }}/${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      publish: false
