name: tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency: ${{ github.workflow }}/${{ github.ref }}

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      publish: true
