on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency: ${{ github.workflow }}/${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      publish: true
